#server 端口号设置
server:
  port: 8761

#注册中心设置，server本身不被发现
eureka:
  instance:
    hostname: localhost
#    每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 1
#    告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
#    waitTimeInMsWhenSyncEmpty: 0
#    #自我保护模式关闭
    enableSelfPreservation: false
    responseCacheUpdateIntervalMs: 3000
    responseCacheAutoExpirationInSeconds: 180
    eviction-interval-timer-in-ms: 3000
## 清理间隔（单位毫秒，默认是60*1000）
#    eviction-interval-timer-in-ms: 100


