server:
  port: 18080
spring:
  application:
    name: monitor
  security:
      user:
        name: wuto6001
        password: 123456
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
            user:
              name: wuto6001
              password: 123456
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
